[package]
name = "nupe"
version = "0.0.0"
edition = "2021"
license = "MIT"
description = "reserved"

[dependencies]
bitflags = "2.1.0"

[features]
default = ["std"]
std = []

[dev-dependencies]
anyhow = "1.0.70"
static_assertions = "1.1.0"
